version: '3.9'

services:
  db:
    image: postgres:15
    container_name: my_postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - ./dump_db.sql:/docker-entrypoint-initdb.d/dump_db.sql:ro

  web:
    build: .
    container_name: fastapi_app
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"

volumes:
  postgres_data:
