"""Add organization_activity many-to-many table

Revision ID: ba0c3e3ebbe1
Revises: 968670589d1b
Create Date: 2025-10-23 20:35:44.319433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba0c3e3ebbe1'
down_revision: Union[str, Sequence[str], None] = '968670589d1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_activity',
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('organization_id', 'activity_id')
    )
    op.drop_constraint(op.f('organization_activity_id_fkey'), 'organization', type_='foreignkey')
    op.drop_column('organization', 'activity_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('activity_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('organization_activity_id_fkey'), 'organization', 'activity', ['activity_id'], ['id'])
    op.drop_table('organization_activity')
    # ### end Alembic commands ###
